#pragma once


enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_TEMP, DIR_SCREW, DIR_GUIDE, DIR_END };
enum OBJ_LIST { OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_MOUSE, OBJ_WALL, OBJ_SHIELD, OBJ_END};